### ISSUE TITLE
The BigInt shim seems to cause TypeScript/Webpack compilation to hang forever. 

### ISSUE THREAD

**Issue by me4502** [janispritzkau/nbt-ts#2]
I'm not sure why - but removing the file and its import fixes it.

This can be reproduced with any webpack build, such as NextJS. 

This project here (https://github.com/EngineHub/enginehub-website/tree/feature/worldedit-golf/golf) hangs forever when building unless the file is manually erased from the node_modules folder and the import is removed. Webpack is used in this build.

**Comment by janispritzkau** [comment]
I've found that Babel doesn't support the BigInt notation and gives this error: `Identifier directly after number`. Not sure what would cause the hanging though.

This could be fixed by replacing the notation `0n` with the BigInt constructor `BigInt(0)`.

But I think that it's better to avoid the shim altogether and do a bit more of manual work to read, write BigInts or to use a `DataView` which also has methods for bigints.

The BigInt Buffer methods are part of Node 12 and it will take some time until that's the standart version of node.

**Comment by janispritzkau** [comment]
I switched to using `DataView` again. It might be useful to include `@babel/plugin-syntax-bigint` if you're using bigint syntax.

**Comment by me4502** [comment]
Nice, that's fixed it for me. Thanks! :)
